DROP TABLE IF EXISTS Movie
CREATE TABLE dbo.Movie (
	MovieId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MovieName VARCHAR(256) NOT NULL,
	FileLocation VARCHAR(500) NOT NULL,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO

DROP TABLE IF EXISTS Genre
CREATE TABLE dbo.Genre(
	GenreId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	GenreName VARCHAR(256) NOT NULL,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO


DROP TABLE IF EXISTS MovieGenre
CREATE TABLE dbo.MovieGenre(
	MovieGenreId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MovieId INT FOREIGN KEY	REFERENCES Movie(MovieId) ON DELETE CASCADE ON UPDATE NO ACTION,
	GenreId INT FOREIGN KEY REFERENCES Genre(GenreId) ON DELETE CASCADE ON UPDATE NO ACTION,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO

DROP TABLE IF EXISTS StaffType
CREATE TABLE dbo.StaffType(
	StaffTypeId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StaffTypeDescription VARCHAR(500),
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO

DROP TABLE IF EXISTS ContactInfo
CREATE TABLE dbo.ContactInfo(
	ContactInfoId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	City VARCHAR(100) NULL,
	StateProvince VARCHAR(2) NULL,
	ZipCode VARCHAR(5) NULL,
	County VARCHAR(50) NULL,
	PhontNumber VARCHAR(20) NULL,
	Fax VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO

DROP TABLE IF EXISTS Staff
CREATE TABLE dbo.Staff(
	StaffId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Gender VARCHAR(1) NOT NULL,
	PrimaryContactInfoId INT FOREIGN KEY REFERENCES ContactInfo(ContactInfoId) ON DELETE CASCADE ON UPDATE NO ACTION,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO

DROP TABLE IF EXISTS MovieStaffXReference
CREATE TABLE dbo.MovieStaffXReference(
	MovieId INT FOREIGN KEY REFERENCES Movie(MovieId),
	StaffTypeId INT FOREIGN KEY REFERENCES StaffType(StaffTypeId),
	StaffId INT FOREIGN KEY REFERENCES Staff(StaffId),
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO