DROP TABLE IF EXISTS Movie

CREATE TABLE dbo.Movie (
	MovieId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MovieName VARCHAR(256) NOT NULL,
	FileLocation VARCHAR(500) NOT NULL,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO

DROP TABLE IF EXISTS Genre
CREATE TABLE dbo.Genre(
	GenreId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	GenreName VARCHAR(256) NOT NULL,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO


DROP TABLE IF EXISTS MovieGenre
CREATE TABLE dbo.MovieGenre(
	MovieGenreId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MovieId INT FOREIGN KEY	REFERENCES Movie(MovieId) ON DELETE CASCADE ON UPDATE NO ACTION,
	GenreId INT FOREIGN KEY REFERENCES Genre(GenreId ) ON DELETE CASCADE ON UPDATE NO ACTION,
	CreatedBy INT NOT NULL DEFAULT 0,
	CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	UpdatedBy INT NOT NULL DEFAULT 0,
	UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE()
)
GO